spring.application.name=app-spring-api-lab
server.port=8081
spring.modulith.runtime.verification-enabled=true
#Determina il profilo da leggere
spring.profiles.active=@activatedProperties@

# http://localhost:8081/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs