spring.application.name=app-spring-api-lab
server.port=8081
spring.modulith.runtime.verification-enabled=true
#Determina il profilo da leggere
spring.profiles.active=@activatedProperties@

# http://localhost:8081/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.override-with-generic-response=false
springdoc.group-configs[0].group=utenti
springdoc.group-configs[0].displayName=Gestione Utenti
#springdoc.group-configs[0].packages-to-scan=com.blackphoenixproductions.appspringapilab.utente.api
springdoc.group-configs[0].paths-to-match=/api/v1/utenti/**

springdoc.group-configs[1].group=documenti
springdoc.group-configs[1].displayName=Gestione Documentale
#springdoc.group-configs[1].packages-to-scan=com.blackphoenixproductions.appspringapilab.utente.api
springdoc.group-configs[1].paths-to-match=/api/v1/documenti/**