#==================================
# = Datasource configuration
#==================================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# http://localhost:8081/h2-console/

# Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/spring-api-lab

# Swagger UI OAuth2 locale per simulare front-end
app.security.oauth2.authorization-url=http://localhost:8080/realms/spring-api-lab/protocol/openid-connect/auth
app.security.oauth2.token-url=http://localhost:8080/realms/spring-api-lab/protocol/openid-connect/token

springdoc.swagger-ui.oauth.client-id=api-lab-iam-client
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.persist-authorization=true